[supervisord]
nodaemon=true

[program:tracker-server]
command=/opt/tracker-server/build/tracker-server /opt/tracker-server/config/tracker.conf
autostart=true
autorestart=true
stderr_logfile=/var/log/tracker-server.err.log
stdout_logfile=/var/log/tracker-server.out.log
environment=PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
directory=/opt/tracker-server
